// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDau3DG38RGkjCkZp5ZXtXw3Nmmj8Du94k',
    appId: '1:218518500574:web:293174536dd75a99483e4f',
    messagingSenderId: '218518500574',
    projectId: 'health-hive-42ecc',
    authDomain: 'health-hive-42ecc.firebaseapp.com',
    storageBucket: 'health-hive-42ecc.firebasestorage.app',
    measurementId: 'G-7JJ4397E05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABEW8BnPCLKTGkoFXD29bz58AyUznIjow',
    appId: '1:218518500574:android:8bf10bfcce7a52fe483e4f',
    messagingSenderId: '218518500574',
    projectId: 'health-hive-42ecc',
    storageBucket: 'health-hive-42ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeKczfd5-GXLtS2FKH8_093s63AjTcrM',
    appId: '1:218518500574:ios:bd76a8371e426af4483e4f',
    messagingSenderId: '218518500574',
    projectId: 'health-hive-42ecc',
    storageBucket: 'health-hive-42ecc.firebasestorage.app',
    iosBundleId: 'com.example.healthHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeKczfd5-GXLtS2FKH8_093s63AjTcrM',
    appId: '1:218518500574:ios:bd76a8371e426af4483e4f',
    messagingSenderId: '218518500574',
    projectId: 'health-hive-42ecc',
    storageBucket: 'health-hive-42ecc.firebasestorage.app',
    iosBundleId: 'com.example.healthHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDau3DG38RGkjCkZp5ZXtXw3Nmmj8Du94k',
    appId: '1:218518500574:web:1bf74b4dc4117081483e4f',
    messagingSenderId: '218518500574',
    projectId: 'health-hive-42ecc',
    authDomain: 'health-hive-42ecc.firebaseapp.com',
    storageBucket: 'health-hive-42ecc.firebasestorage.app',
    measurementId: 'G-1L12CG8YES',
  );
}
